name: build

on: workflow_dispatch

jobs:
  build:
      runs-on: ubuntu-latest
      container: archlinux:latest
      steps:
        - name: running 
          run: |
              pacman -Sy -y
              pacman -Sy rust -y
              cargo --version
          
