name: build

on: workflow_dispatch

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup JDK
          uses: actions/setup-java@v5
          with:
            distribution: temurin
            java-version: 22
            check-latest: true
            
        - name: running 
          run: |
              git clone https://github.com/OpenXiangShan/XiangShan.git
              cd XianShan
              docker build -t cpu .
              docker run cpu
              
        
