name: Run

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    container:
      image: debian:latest
    steps:
      - name: Running
        run: apt update && apt install fastfetch -y && fastfetch
